import { Inter } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { AuthProvider } from "./Providers";
import { ThemeProvider } from "./(components)/theme-provider";
import "@radix-ui/themes/styles.css";
import NavWrap from "./(components)/NavWrap";
import { Theme, ThemePanel } from "@radix-ui/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CrescentByte",
  description: "Generated by a team looking for internships.",
};

// we import provider here and wrap the childern with it
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <NavWrap>{children}</NavWrap>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
